"""Small, ownership-aware installer for the skills shipped inside this wheel."""

from __future__ import annotations

import argparse
import hashlib
import importlib
import json
import os
import shlex
import shutil
import sys
import tempfile
from importlib import resources
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path, PurePosixPath

from . import (BUSINESS_MODULE, PRODUCT, RUNTIME_MODULES, RUNTIME_SKILLS, SKILLS,
               SOURCE_PARENT_LEVEL, SOURCE_SCRIPT, SOURCE_SKILL_BASE)

MANIFEST = ".skill-install.json"
HOSTS = ("codex", "claude-code", "dsh", "opencode")
PROJECT_DIRS = {
    "codex": (".agents", "skills"),
    "claude-code": (".claude", "skills"),
    "dsh": (".dsh", "skills"),
    "opencode": (".opencode", "skills"),
}
USER_DIRS = {
    "codex": (".agents", "skills"),
    "claude-code": (".claude", "skills"),
    "dsh": (".dsh", "skills"),
    "opencode": (".config", "opencode", "skills"),
}


class InstallError(Exception):
    """An actionable input, dependency, or ownership conflict."""


def _digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _runtime_python() -> Path:
    return Path(sys.executable).absolute()


def _with_runtime(skill_bytes: bytes) -> bytes:
    python = str(_runtime_python())
    command = shlex.quote(python)
    lines = [
        "\n## Installed runtime (generated by ddp-install)",
        f"Python executable: `{python}`. Use it as one argument, even when its path contains spaces.",
        "Replace bare CLI names in the examples below with these absolute entry points; no PATH or source checkout is required:",
        *(f"- `{module}`: `{command} -m {module}`" for module in RUNTIME_MODULES),
        "Re-run `ddp-install upgrade` after moving or reinstalling the tool environment.\n",
    ]
    note = ("\n".join(lines) + "\n").encode("utf-8")
    closing = skill_bytes.find(b"\n---\n", 4) if skill_bytes.startswith(b"---\n") else -1
    position = closing + len(b"\n---\n") if closing >= 0 else 0
    return skill_bytes[:position] + note + skill_bytes[position:]


def _release_version() -> str:
    try:
        return version(PRODUCT)
    except PackageNotFoundError:
        return "source"


def _runtime_check() -> None:
    try:
        importlib.import_module(BUSINESS_MODULE)
    except (ImportError, OSError) as exc:
        missing = getattr(exc, "name", None) or BUSINESS_MODULE
        raise InstallError(
            f"runtime dependency {missing!r} is unavailable ({exc}); "
            f"reinstall {PRODUCT} with dependencies using uv tool install --reinstall <package-or-wheel>"
        ) from exc


def _resource_files(skill: str) -> dict[str, bytes]:
    root = resources.files(__package__).joinpath("resources", skill)
    source_root: Path | None = None
    if not root.is_dir():
        # Development checkouts use the same canonical files as the wheel build.
        # A wheel without embedded resources never reaches into an author checkout.
        location = Path(__file__).resolve()
        candidate = location.parents[SOURCE_PARENT_LEVEL]
        if (
            not {"site-packages", "dist-packages"}.intersection(location.parts)
            and (candidate / "pyproject.toml").is_file()
        ):
            source_root = candidate
            root = candidate / SOURCE_SKILL_BASE / skill
    if not root.is_dir():
        raise InstallError(f"wheel is missing skill resource {skill!r}; rebuild {PRODUCT} from its release source")
    found: dict[str, bytes] = {}

    def collect(node, prefix: PurePosixPath) -> None:
        for child in node.iterdir():
            rel = prefix / child.name
            if child.is_dir():
                collect(child, rel)
            elif child.is_file():
                found[rel.as_posix()] = child.read_bytes()

    collect(root, PurePosixPath())
    if source_root is not None and SOURCE_SCRIPT is not None and skill == "design-doc-protocol":
        helper = source_root / SOURCE_SCRIPT
        if not helper.is_file():
            raise InstallError(f"checkout is missing skill script {helper}; rebuild the release")
        found["scripts/workflow.py"] = helper.read_bytes()
    if "SKILL.md" not in found:
        raise InstallError(f"wheel skill {skill!r} has no SKILL.md; rebuild the release")
    if skill in RUNTIME_SKILLS:
        found["SKILL.md"] = _with_runtime(found["SKILL.md"])
    return found


def _read_manifest(destination: Path, skill: str) -> dict | None:
    path = destination / MANIFEST
    if not path.exists():
        return None
    if path.is_symlink():
        raise InstallError(f"refusing symlinked ownership manifest: {path}")
    try:
        manifest = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        raise InstallError(f"cannot read ownership manifest {path}: {exc}") from exc
    if not isinstance(manifest, dict) or manifest.get("product") != PRODUCT or manifest.get("skill") != skill:
        raise InstallError(f"{path} belongs to another product or is invalid; inspect it before changing this skill")
    files = manifest.get("files")
    if not isinstance(files, dict) or any(
        not isinstance(name, str)
        or not isinstance(digest, str)
        or digest != digest.lower()
        or len(digest) != 64
        or not name
        or "\\" in name
        or PurePosixPath(name).is_absolute()
        or ".." in PurePosixPath(name).parts
        or PurePosixPath(name).as_posix() != name
        or name == MANIFEST
        for name, digest in files.items()
    ):
        raise InstallError(f"invalid file list in {path}; inspect it before changing this skill")
    return manifest


def _check_existing(destination: Path, tracked: dict[str, str], *, allow_missing: bool = False) -> None:
    for rel, expected in tracked.items():
        path = destination / rel
        if path.is_symlink() or any(parent.is_symlink() for parent in path.parents if parent != destination.parent):
            raise InstallError(f"refusing symlinked installed path: {path}")
        if not path.exists():
            if allow_missing:
                continue
            raise InstallError(f"installed file was removed: {path}; restore it or resolve ownership manually")
        if not path.is_file() or _digest(path.read_bytes()) != expected:
            raise InstallError(f"user-modified installed file: {path}; save your edits before upgrading or uninstalling")


def _check_symlinks(destination: Path) -> None:
    if destination.is_symlink():
        raise InstallError(f"refusing symlinked skill directory: {destination}")
    if destination.exists():
        for path in destination.rglob("*"):
            if path.is_symlink():
                raise InstallError(f"refusing symlink within skill directory: {path}")


def _recover_backup(destination: Path) -> None:
    backup = destination.with_name(f".{destination.name}.{PRODUCT}.backup")
    if not backup.exists():
        return
    if destination.exists():
        raise InstallError(
            f"both {destination} and recovery backup {backup} exist; inspect them before retrying"
        )
    backup.rename(destination)


def _install_one(root: Path, skill: str) -> str:
    root.mkdir(parents=True, exist_ok=True)
    destination = root / skill
    _recover_backup(destination)
    _check_symlinks(destination)
    desired = _resource_files(skill)
    prior = _read_manifest(destination, skill) if destination.exists() else None
    if destination.exists() and prior is None:
        raise InstallError(f"{destination} already exists without a {PRODUCT} ownership manifest; choose another directory")
    tracked = prior["files"] if prior else {}
    if prior:
        _check_existing(destination, tracked)
    for rel in desired:
        path = destination / rel
        if path.exists() and rel not in tracked:
            raise InstallError(f"unowned file conflicts with release: {path}; move it before installing")
    hashes = {name: _digest(data) for name, data in desired.items()}
    if prior and tracked == hashes and prior.get("version") == _release_version():
        return f"unchanged {destination}"

    stage = Path(tempfile.mkdtemp(prefix=f".{skill}.stage-", dir=root))
    backup = destination.with_name(f".{skill}.{PRODUCT}.backup")
    try:
        if destination.exists():
            shutil.copytree(destination, stage, dirs_exist_ok=True)
            for rel in tracked.keys() - hashes.keys():
                (stage / rel).unlink()
        for rel, data in desired.items():
            target = stage / rel
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(data)
        manifest = {
            "product": PRODUCT,
            "skill": skill,
            "version": _release_version(),
            "runtime_python": str(_runtime_python()),
            "files": hashes,
        }
        (stage / MANIFEST).write_text(json.dumps(manifest, sort_keys=True, indent=2) + "\n", encoding="utf-8")
        if destination.exists():
            destination.rename(backup)
            try:
                stage.rename(destination)
            except OSError:
                backup.rename(destination)
                raise
            shutil.rmtree(backup)
        else:
            stage.rename(destination)
    finally:
        if stage.exists():
            shutil.rmtree(stage)
    return f"installed {destination}"


def _uninstall_one(root: Path, skill: str) -> str:
    destination = root / skill
    _recover_backup(destination)
    if not destination.exists():
        return f"absent {destination}"
    _check_symlinks(destination)
    prior = _read_manifest(destination, skill)
    if prior is None:
        raise InstallError(f"{destination} has no {PRODUCT} ownership manifest; refusing to remove it")
    _check_existing(destination, prior["files"], allow_missing=True)
    for rel in prior["files"]:
        path = destination / rel
        if path.exists():
            path.unlink()
    (destination / MANIFEST).unlink()
    for directory in sorted((p for p in destination.rglob("*") if p.is_dir()), key=lambda p: len(p.parts), reverse=True):
        if not any(directory.iterdir()):
            directory.rmdir()
    if not any(destination.iterdir()):
        destination.rmdir()
    return f"uninstalled {destination}; user files preserved"


def _targets(args: argparse.Namespace) -> list[Path]:
    if args.dir:
        return [Path(args.dir).expanduser().resolve()]
    hosts = args.host or []
    if not hosts:
        raise InstallError("choose --host codex|claude-code|dsh|opencode|all, or --dir PATH; use --interactive for prompts")
    if "all" in hosts:
        hosts = list(HOSTS)
    hosts = list(dict.fromkeys(hosts))
    if args.scope == "project":
        project = Path(args.project or Path.cwd()).expanduser().resolve()
        if not project.is_dir():
            raise InstallError(f"project directory does not exist: {project}")
        bases = [project.joinpath(*PROJECT_DIRS[host]) for host in hosts]
    else:
        bases = []
        for host in hosts:
            if host == "dsh" and os.environ.get("DSH_HOME"):
                bases.append(Path(os.environ["DSH_HOME"]).expanduser() / "skills")
            elif host == "opencode" and os.environ.get("XDG_CONFIG_HOME"):
                bases.append(Path(os.environ["XDG_CONFIG_HOME"]).expanduser() / "opencode" / "skills")
            else:
                bases.append(Path.home().joinpath(*USER_DIRS[host]))
    return list(dict.fromkeys(bases))


def _prompt(args: argparse.Namespace) -> None:
    choice = input("Host (codex/claude-code/dsh/opencode/all/custom): ").strip().lower()
    if choice == "custom":
        args.dir = input("Skill parent directory: ").strip()
        if not args.dir:
            raise InstallError("custom directory cannot be empty")
        return
    if choice not in (*HOSTS, "all"):
        raise InstallError(f"unknown host {choice!r}")
    args.host = [choice]
    scope = input("Scope (project/user) [project]: ").strip().lower() or "project"
    if scope not in ("project", "user"):
        raise InstallError(f"unknown scope {scope!r}")
    args.scope = scope
    if scope == "project":
        args.project = input(f"Project directory [{Path.cwd()}]: ").strip() or str(Path.cwd())


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog=f"{PRODUCT}-install",
        description=f"Install {PRODUCT} wheel-bundled agent skills without changing host configuration",
    )
    sub = parser.add_subparsers(dest="command", required=True)
    for command in ("install", "upgrade", "doctor", "uninstall"):
        part = sub.add_parser(command)
        part.add_argument("--host", action="append", choices=(*HOSTS, "all"), help="Repeat for multiple hosts")
        part.add_argument("--scope", choices=("project", "user"), default="project")
        part.add_argument("--project", help="Project root; used only with project scope")
        part.add_argument("--dir", help="Explicit parent directory for skills; overrides host and scope")
        part.add_argument("--interactive", action="store_true", help="Ask for host and path even when stdin is redirected")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    try:
        if args.command in ("install", "upgrade", "doctor"):
            _runtime_check()
        for skill in SKILLS:
            _resource_files(skill)
        if args.interactive or (args.command != "doctor" and not args.host and not args.dir and sys.stdin.isatty()):
            _prompt(args)
        if args.command == "doctor" and not args.host and not args.dir:
            print(f"OK {PRODUCT} {_release_version()}: runtime and {len(SKILLS)} bundled skill(s)")
            return 0
        for root in _targets(args):
            for skill in SKILLS:
                if args.command == "doctor":
                    destination = root / skill
                    _check_symlinks(destination)
                    manifest = _read_manifest(destination, skill)
                    if manifest is None:
                        raise InstallError(f"skill is not installed: {destination}; run {PRODUCT}-install install")
                    _check_existing(destination, manifest["files"])
                    runtime = manifest.get("runtime_python")
                    if isinstance(runtime, str) and runtime and not Path(runtime).is_file():
                        raise InstallError(f"installed runtime no longer exists: {runtime}; reinstall the tool and upgrade this skill")
                    print(f"OK {destination} ({manifest.get('version', 'unknown')})")
                elif args.command == "uninstall":
                    print(_uninstall_one(root, skill))
                else:
                    print(_install_one(root, skill))
        if args.command in ("install", "upgrade"):
            command = shlex.quote(str(_runtime_python()))
            for module in RUNTIME_MODULES:
                print(f"runtime {module}: {command} -m {module}")
        return 0
    except (InstallError, OSError, EOFError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
